### ISSUE TITLE
About the download process

### ISSUE THREAD

**Issue by ghost** [daktak/basketbuild_downloader#11]
Will this automatically check the md5 or sha1 hash when downloading?

Also, can we please get a confirmation to download before they start?

**Comment by daktak** [comment]
Seems no md5 is uploaded for most roms.

I would rather add a cancel button to the download notification than a "Are you sure?" dialog. This appears to come with Android N.

**Comment by ghost** [comment]
What about the apps default rom of aokp? Those do have md5sums.

**Comment by daktak** [comment]
Sorry, can you point me in their direction? https://s.basketbuild.com/devs/aokp/oneplus2 has the build log and zip

**Comment by ghost** [comment]
When you click the download link it will say file md5.

https://s.basketbuild.com/filedl/devs?dev=aokp&dl=aokp/oneplus2/aokp_oneplus2_mm_nightly_2016-07-02.zip

**Comment by daktak** [comment]
Thank you. I've just added md5 checking to afhdownloader so should be able adapt it to this.

**Comment by daktak** [comment]
Added to 0.3 #15
