### ISSUE TITLE
[Feature Request]  Add Refresh Option

### ISSUE THREAD

**Issue by ghost** [daktak/basketbuild_downloader#18]
Is there any chance you can add a button that will refresh the rom list?

The reason I ask is that when the rom is downloaded the md5 check does not check and or start until you make the app reload and the app says, loading.

Thanks!

**Comment by daktak** [comment]
Currently I press back and then re-load the app.

**Comment by ghost** [comment]
So do I.  So is this something that you will implement?

**Comment by ghost** [comment]
or perhaps an automatic refresh after the file is fully downloaded.

**Comment by daktak** [comment]
I would like to do once download is complete, but currently have no hook to trigger that. 
I think I'll add a refresh option.

**Comment by ghost** [comment]
Thank you, and Merry Christmas!

**Comment by daktak** [comment]
merge #19 includes refresh option.
